services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/DL.GameOfLife.Api/Dockerfile
    container_name: cgol-backend-container
    ports:
      - "5217:5217"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbOptions__ConnectionString=mongodb://root:root@database:27017/cgol?authSource=admin&authMechanism=SCRAM-SHA-1
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: cgol-mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: cgol
    volumes:
      - cgol_mongodb_data:/data/db

volumes:
  cgol_mongodb_data: